# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-03 16:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_remove_employees_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='uploadphone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.IntegerField()),
                ('employee', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='polls.employees')),
            ],
        ),
    ]
