# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-03 18:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_uploadphone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadphone',
            name='phone',
            field=models.BigIntegerField(),
        ),
    ]
