# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-03 19:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_auto_20180103_2352'),
    ]

    operations = [
        migrations.CreateModel(
            name='receiverequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receive_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receive_id', to='polls.employees')),
                ('request_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='request_id', to='polls.employees')),
            ],
        ),
    ]
