# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-03 20:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0006_receiverequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(max_length=150)),
                ('post', models.TextField()),
                ('date', models.DateTimeField(default='')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.employees')),
            ],
        ),
    ]
